CREATE DATABASE IF NOT EXISTS `testdb`;
USE testdb;
CREATE TABLE IF NOT EXISTS todos (
    id INT AUTO_INCREMENT,
    title VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
